const fs = require('fs');
const path = require('path');

// 物品名称翻译映射
const translations = {
  'Cactus': '仙人掌',
  'TV Stand': '电视柜',
  'Dining table': '餐桌',
  'Single Bed': '单人床',
  'Livingroom Chair': '客厅椅',
  'Small Plant': '小植物',
  'Column': '柱子',
  'Barbell': '杠铃',
  'Toy': '玩具',
  'Barbell Stand': '杠铃架',
  'Books': '书籍',
  'Stool': '凳子',
  'Pool table': '台球桌',
  'Bookshelf': '书架',
  'Coat Rack': '衣架',
  'Car Toy': '玩具车',
  'Bedside Table': '床头柜',
  'Sofa': '沙发',
  'Bunkbed': '双层床',
  'My leather couch': '我的皮沙发',
  'Office Table': '办公桌',
  'Dining Table': '餐桌',
  'Guitar': '吉他',
  'Trash Bin': '垃圾桶',
  'Recessed Light': '嵌入式灯',
  'Shelf': '架子',
  'Table Lamp': '台灯',
  'Ceiling Lamp': '吸顶灯',
  'Closet': '衣柜',
  'Coffee Table': '茶几',
  'Dining Chair': '餐椅',
  'Dresser': '梳妆台',
  'Ikea Kallax 2x4': '宜家 Kallax 2x4',
  'Indoor Plant': '室内植物',
  'Ironing Board': '熨衣板',
  'Double Bed': '双人床',
  'Floor Lamp': '落地灯',
  'Herman Miller Aeron': 'Herman Miller Aeron 椅',
  'Easel': '画架',
  'Lounge Chair': '躺椅',
  'Office Chair': '办公椅',
  'Piano': '钢琴',
  'Picture': '挂画',
  'Rectangular Carpet': '长方形地毯',
  'Rounded Mirror': '圆形镜子',
  'Round Carpet': '圆形地毯',
  'Threadmill': '跑步机',
  'Standing Desk': '站立式办公桌',
  'Sprinkler': '洒水器',
  'Exit Sign': '出口标志',
  'Sewing Machine': '缝纫机',
  'Television': '电视',
  'Power Outlet': '电源插座',
  'AC block': '空调外机',
  'Stereo Speaker': '音响',
  'Thermostat': '温控器',
  'Toaster': '烤面包机',
  'Kettle': '电水壶',
  'Hydrant': '消防栓',
  'Fire Detector': '火灾探测器',
  'Smoke Detector': '烟雾探测器',
  'Coffee Machine': '咖啡机',
  'Ceiling fan': '吊扇',
  'Iron': '熨斗',
  'Air Conditioning': '空调',
  'Computer': '电脑',
  'Alarm Keypad': '报警键盘',
  'Electric Panel': '配电箱',
  'Bathroom Sink': '浴室水槽',
  'Angle Shower': '转角淋浴',
  'Toilet Paper': '卫生纸',
  'Washing Machine': '洗衣机',
  'Shower Rug': '淋浴垫',
  'Bathtub': '浴缸',
  'Laundry Bag': '洗衣袋',
  'Squared Shower': '方形淋浴',
  'Drying Rack': '晾衣架',
  'Toilet': '马桶',
  'Microwave': '微波炉',
  'Cutting Board': '砧板',
  'Kitchen Utensils': '厨房用具',
  'Kitchen Counter': '厨房台面',
  'Hood': '油烟机',
  'Kitchen Bar': '厨房吧台',
  'Kitchen Cabinet': '厨房橱柜',
  'Kitchen': '厨房',
  'Frying Pan': '煎锅',
  'Fruits': '水果',
  'Fridge': '冰箱',
  'Kitchen Shelf': '厨房置物架',
  'Wine Bottle': '葡萄酒瓶',
  'Stove': '炉灶',
  'Ball': '球',
  'Bush': '灌木',
  'Basketball Hoop': '篮球框',
  'Parking Spot': '停车位',
  'Palm': '棕榈树',
  'Sunbed': '躺椅',
  'Fir': '冷杉树',
  'Tree': '树',
  'Skate': '滑板',
  '1967 Chevrolet Camaro': '1967 雪佛兰科迈罗',
  'Outdoor Playhouse': '户外游戏屋',
  'Patio Umbrella': '庭院伞',
  'Pillar': '柱子',
  'Scooter': '滑板车',
  'Tesla Model Y': '特斯拉 Model Y',
  'Dishwasher': '洗碗机',
  'Fireplace': '壁炉'
};

const filePath = path.join(__dirname, 'packages/editor/src/components/ui/item-catalog/catalog-items.tsx');
let content = fs.readFileSync(filePath, 'utf8');

Object.entries(translations).forEach(([en, zh]) => {
  const searchStr = `name: '${en.replace(/'/g, "\\'")}',`;
  const replaceStr = `name: '${zh}',`;
  content = content.split(searchStr).join(replaceStr);
});

fs.writeFileSync(filePath, content, 'utf8');
console.log('物品名称翻译完成！');
